// Deterministic system assertions for the FINAL AUDIT questions.
const { chromium } = await import('playwright').catch(() => import('/opt/node22/lib/node_modules/playwright/index.mjs'));
const browser = await chromium.launch({ executablePath: process.env.CHROME || undefined });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
const load = async () => { await page.goto('file://' + process.cwd() + '/dist/ColonyShipHorror.html?autostart=1&seed=11'); await page.waitForTimeout(500); await page.evaluate(() => { UI.autoPauseOn = false; G.director.update = () => {}; }); };
const T = async (name, fn) => { await load(); const r = await page.evaluate(fn); console.log((r.pass ? 'PASS ' : 'FAIL ') + name + ' — ' + r.info); };

await T('powered pressure door auto-closes on breach', () => { G.doorById.d_wor_qtr.mode = 'open'; G.doorById.d_wor_qtr.anim = 1; breachRoom(G.roomById.workshop, 0.5, 100); G.fastForward(12); return { pass: G.doorById.d_wor_qtr.mode === 'closed', info: `door ${G.doorById.d_wor_qtr.mode}` }; });
await T('breach spreads through a jammed-open door', () => { G.doorById.d_wor_qtr.mode = 'open'; G.doorById.d_wor_qtr.anim = 1; G.doorById.d_wor_qtr.jammed = true; for (const c of G.crew) c.suit = 999; breachRoom(G.roomById.workshop, 0.5, 100); G.fastForward(12); const q = G.roomById.quarters.p; return { pass: q < 90, info: `quarters ${q.toFixed(1)} kPa after 12s with door open` }; });
await T('closing bulkhead contains decompression', () => { setDoorMode(G.doorById.d_wor_qtr, 'closed'); G.doorById.d_wor_qtr.anim = 0; setDoorMode(G.doorById.h_air_wor, 'sealed'); setDoorMode(G.doorById.h_wor_rea, 'sealed'); for (const c of G.crew) { c.suit = 999; if (c.room === 'workshop') { c.room = 'quarters'; c.x = 600; } } for (const c of G.crew) c.task = { type: 'hold', room: c.room }; breachRoom(G.roomById.workshop, 0.5, 100); G.fastForward(12); const q = G.roomById.quarters.p, w = G.roomById.workshop.p; return { pass: q > 95 && w < 40, info: `workshop ${w.toFixed(1)} / quarters ${q.toFixed(1)} kPa` }; });
await T('life support off → O2 stops, rooms degrade', () => { setGroup('LIFE', false); const o0 = G.res.o2; G.fastForward(240); const avg = G.rooms.reduce((a, r) => a + effO2(r), 0) / 12; return { pass: avg < 20 && G.res.o2 <= o0 + 0.01, info: `avg room O2 ${avg.toFixed(1)}%, reserve ${o0.toFixed(0)}→${G.res.o2.toFixed(0)}` }; });
await T('security off → cameras lost + locks release', () => { setDoorMode(G.doorById.d_med_qua, 'locked'); setGroup('SEC', false); G.fastForward(1); const blind = G.rooms.filter((r) => !r.observed).length; return { pass: blind === 12 && effectiveMode(G.doorById.d_med_qua) === 'closed', info: `${blind}/12 rooms unobserved, locked door now ${effectiveMode(G.doorById.d_med_qua)}` }; });
await T('reactor damage → deficit → breaker shed', () => { G.roomById.reactor.integ = 35; G.battery = 3; G.fastForward(15); const shed = Object.values(G.groups).filter((g) => g.tripped).map((g) => g.id); return { pass: shed.length > 0, info: `supply ${G.supply.toFixed(0)}/${G.demand}, tripped: ${shed.join(',')}` }; });
await T('crew can become trapped', () => { const c = G.crew[0]; for (const d of roomDoors(G.roomById[c.room])) d.mode = 'sealed'; orderCrew(c, { type: 'move', room: 'bridge' }); return { pass: c.trapped === true, info: `${c.name} in ${c.room} trapped=${c.trapped}` }; });
await T('crew can die (vacuum) and kin react', () => { const a = G.crew.find((c) => c.first === 'Avery'), m = G.crew.find((c) => c.first === 'Marcus'); a.suit = 0; const r = G.roomById[a.room]; const s0 = m.stress, mo0 = m.morale; sealRoom(r); startVent(r); for (const c of G.crew) if (c !== a && c.room === r.id) { c.room = 'mess'; c.x = 1000; } G.fastForward(40); return { pass: !a.alive && m.stress > s0 + 25 && m.grief > 0, info: `Avery alive=${a.alive} (${a.deathCause}); Marcus stress ${s0.toFixed(0)}→${m.stress.toFixed(0)} morale ${mo0.toFixed(0)}→${m.morale.toFixed(0)} grief=${Math.round(m.grief)}` }; });
await T('infection stays hidden from UI, clues accumulate', () => { const c = G.crew[6]; exposeInfection(c, 'test'); G.fastForward(330); UI.select({ type: 'crew', id: 6 }); UI.renderCtx(true); const html = document.getElementById('ctx').innerText + document.getElementById('roster').innerText; return { pass: !/infect/i.test(html) && c.infection.stage >= 1, info: `stage ${c.infection.stage}, temp ${c.bodyTemp.toFixed(1)}, panel mentions infection: ${/infect/i.test(html)}` }; });
await T('organism moves through ducts', () => { const m = spawnCreature('cryo', {}); const seen = new Set(); for (let i = 0; i < 60; i++) { G.fastForward(3); seen.add(m.state === 'vent' ? m.ventRoom : m.room); } return { pass: seen.size >= 3, info: `visited ${[...seen].join(', ')}` }; });
await T('sealed + vented room kills organism', () => { const m = spawnCreature('o2', { inRoom: true, x: 800 }); for (const c of G.crew) if (c.room === 'o2') { c.room = 'mess'; c.x = 1000; } sealRoom(G.roomById.o2); startVent(G.roomById.o2); G.fastForward(40); return { pass: !m.alive, info: `alive=${m.alive}, hp ${Math.round(m.hp)}` }; });
await T('lighting reflects power: room unpowered', () => { setGroup('HAB', false); G.fastForward(1); return { pass: !G.roomById.mess.powered && G.roomById.bridge.powered, info: `mess powered=${G.roomById.mess.powered}` }; });
await T('fire spreads through a jammed-open door, starves in vacuum', () => { G.doorById.d_qtr_mes.mode = 'open'; G.doorById.d_qtr_mes.anim = 1; G.doorById.d_qtr_mes.jammed = true; igniteRoom(G.roomById.mess, 1); let spread = false; for (let i = 0; i < 60 && !spread; i++) { G.fastForward(2); spread = G.roomById.quarters.fire > 0 || G.roomById.hydro.fire > 0; } sealRoom(G.roomById.mess); startVent(G.roomById.mess); G.fastForward(20); return { pass: spread && G.roomById.mess.fire === 0, info: `spread=${spread}, mess fire after vent ${G.roomById.mess.fire.toFixed(2)}` }; });
console.log(errs.length ? errs.join('\n') : 'no page errors');
await browser.close();
