// Plays the FIRST WATCH tutorial through the real UI, screenshotting each step.
const { chromium } = await import('playwright').catch(() => import('/opt/node22/lib/node_modules/playwright/index.mjs'));
import { mkdirSync } from 'node:fs';
const OUT = process.env.SHOT_DIR || 'shots'; mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME || undefined });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
const errs = []; page.on('pageerror', (e) => errs.push(e.message + e.stack));
await page.goto('file://' + process.cwd() + '/dist/ColonyShipHorror.html?seed=4');
await page.waitForTimeout(5200);
await page.screenshot({ path: OUT + '/tut_00_title.png' });
await page.click('#btnStart');
const step = () => page.evaluate(() => `${G.tut.active ? TUT.steps[G.tut.i].id : 'DONE'} sub=${G.tut.sub}`);
const shot = async (n) => { await page.waitForTimeout(400); await page.screenshot({ path: `${OUT}/tut_${n}.png` }); console.log(n, await step()); };
await page.waitForTimeout(1500); await shot('01_look');
await page.waitForTimeout(17000); await shot('01b_look_tour');
await page.mouse.move(900, 500); await page.mouse.wheel(0, -300); await page.waitForTimeout(600);
await shot('02_room');
const roomPt = (id) => page.evaluate((id) => { const r = G.roomById[id]; return w2s(r.cx, r.cy); }, id);
let p = await roomPt('o2'); await page.mouse.click(p[0], p[1]); await shot('02b_room_selected');
await page.click('#tutCont'); await shot('03_crew');
await page.click('#cr_2'); await shot('03b_crew_selected');
await page.click('#tutCont'); await shot('04_order');
await page.waitForTimeout(800); p = await roomPt('hydro'); await page.mouse.click(p[0], p[1], { button: 'right' }); await page.waitForTimeout(200);
await page.click('#menu button:has-text("REPAIR")'); await shot('04b_ordered');
for (let i = 0; i < 40 && (await step()).startsWith('order'); i++) await page.waitForTimeout(1000);
await shot('05_power');
await page.click('#pg_HAB button'); await page.waitForTimeout(1500); await shot('05b_hab_off');
await page.click('#pg_HAB button'); await shot('06_leak');
const dp = await page.evaluate(() => { const d = G.doorById.d_air_sec; return w2s(d.x, G.roomById.airlock.fy - 25); });
await page.waitForTimeout(2500); await shot('06a_leak_progress');
await page.mouse.click(dp[0], dp[1]); await page.waitForTimeout(200);
await page.click('#menu button:has-text("CLOSE")'); await shot('06b_closed');
for (let i = 0; i < 20 && (await step()).startsWith('leak'); i++) await page.waitForTimeout(1000);
await shot('07_camera');
await page.click('#tutCont'); await page.waitForTimeout(1500); await shot('08_done');
console.log('dirT', await page.evaluate(() => G.dirT.toFixed(0)), 't', await page.evaluate(() => G.t.toFixed(0)));
console.log(errs.join('\n') || 'no errors');
await browser.close();
